DROP TABLE IF EXISTS provinsi;
CREATE TABLE provinsi (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nama VARCHAR(255) NOT NULL,
  presentase_tunjangan DOUBLE NOT NULL,

  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS jabatan;
CREATE TABLE jabatan (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nama VARCHAR(255) NOT NULL,
  deskripsi VARCHAR(255) NOT NULL,
  gaji_pokok DOUBLE NOT NULL,

  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS instansi;
CREATE TABLE instansi (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nama VARCHAR(255) NOT NULL,
  deskripsi VARCHAR(255) NOT NULL,
  id_provinsi BIGINT NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (id_provinsi) REFERENCES provinsi(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

DROP TABLE IF EXISTS pegawai;
CREATE TABLE pegawai (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nip VARCHAR(255) NOT NULL,
  nama VARCHAR(255) NOT NULL,
  tempat_lahir VARCHAR(255) NOT NULL,
  tanggal_lahir DATE NOT NULL,
  tahun_masuk VARCHAR(255) NOT NULL,
  id_instansi BIGINT NOT NULL,

  UNIQUE (nip),
  PRIMARY KEY (id),
  FOREIGN KEY (id_instansi) REFERENCES instansi(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

DROP TABLE IF EXISTS jabatan_pegawai;
CREATE TABLE jabatan_pegawai (
  id BIGINT NOT NULL AUTO_INCREMENT,
  id_pegawai BIGINT NOT NULL,
  id_jabatan BIGINT NOT NULL,

  PRIMARY KEY(id),
  FOREIGN KEY (id_pegawai) REFERENCES pegawai(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (id_jabatan) REFERENCES jabatan(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

